export const CATEGORY_ERRORS = {
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_NOT_OWNER: 'CATEGORY_NOT_OWNER',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',
  CATEGORY_SYSTEM_IMMUTABLE: 'CATEGORY_SYSTEM_IMMUTABLE',
  CATEGORY_INVALID_DIRECTION: 'CATEGORY_INVALID_DIRECTION',
  CATEGORY_INVALID_SCOPE: 'CATEGORY_INVALID_SCOPE',
  CATEGORY_SLUG_CONFLICT: 'CATEGORY_SLUG_CONFLICT',
  CATEGORY_GROUP_NOT_MEMBER: 'CATEGORY_GROUP_NOT_MEMBER',
  CATEGORY_GROUP_NOT_ADMIN: 'CATEGORY_GROUP_NOT_ADMIN',
  CATEGORY_REPLACEMENT_INVALID: 'CATEGORY_REPLACEMENT_INVALID',
} as const;

export type CategoryErrorCode = (typeof CATEGORY_ERRORS)[keyof typeof CATEGORY_ERRORS];
