/**
 * Transaction-domain error codes — see design §5.7.
 *
 * Only the subset used by the POST /transactions (ONE_TIME) endpoint lives here
 * for iteration 6.5. Later iterations (list/get/edit/delete, stars, comments,
 * RECURRING, INSTALLMENT) will extend this union.
 */
export const TRANSACTION_ERRORS = {
  TRANSACTION_INVALID_AMOUNT: 'TRANSACTION_INVALID_AMOUNT',
  TRANSACTION_INVALID_DATE: 'TRANSACTION_INVALID_DATE',
  TRANSACTION_INVALID_CURRENCY: 'TRANSACTION_INVALID_CURRENCY',
  TRANSACTION_INVALID_CATEGORY: 'TRANSACTION_INVALID_CATEGORY',
  TRANSACTION_CATEGORY_DIRECTION_MISMATCH: 'TRANSACTION_CATEGORY_DIRECTION_MISMATCH',
  TRANSACTION_NO_ATTRIBUTIONS: 'TRANSACTION_NO_ATTRIBUTIONS',
  TRANSACTION_INVALID_ATTRIBUTION: 'TRANSACTION_INVALID_ATTRIBUTION',
  TRANSACTION_ATTRIBUTION_OUT_OF_SCOPE: 'TRANSACTION_ATTRIBUTION_OUT_OF_SCOPE',
  TRANSACTION_DUPLICATE_ATTRIBUTION: 'TRANSACTION_DUPLICATE_ATTRIBUTION',
  TRANSACTION_SCHEDULE_NOT_SUPPORTED: 'TRANSACTION_SCHEDULE_NOT_SUPPORTED',
  TRANSACTION_PLAN_NOT_SUPPORTED: 'TRANSACTION_PLAN_NOT_SUPPORTED',
  TRANSACTION_TYPE_NOT_IMPLEMENTED: 'TRANSACTION_TYPE_NOT_IMPLEMENTED',
  TRANSACTION_SCOPE_NOT_ACCESSIBLE: 'TRANSACTION_SCOPE_NOT_ACCESSIBLE',
  TRANSACTION_INVALID_CURSOR: 'TRANSACTION_INVALID_CURSOR',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_NOT_OWNER: 'TRANSACTION_NOT_OWNER',
  TRANSACTION_CANNOT_EDIT_GENERATED_OCCURRENCE: 'TRANSACTION_CANNOT_EDIT_GENERATED_OCCURRENCE',
  TRANSACTION_SCOPE_AMBIGUOUS: 'TRANSACTION_SCOPE_AMBIGUOUS',
  TRANSACTION_SCOPE_NOT_ATTRIBUTED: 'TRANSACTION_SCOPE_NOT_ATTRIBUTED',
  TRANSACTION_NO_ACCESSIBLE_ATTRIBUTION: 'TRANSACTION_NO_ACCESSIBLE_ATTRIBUTION',
  TRANSACTION_COMMENT_NOT_FOUND: 'TRANSACTION_COMMENT_NOT_FOUND',
  TRANSACTION_COMMENT_NOT_AUTHOR: 'TRANSACTION_COMMENT_NOT_AUTHOR',
  TRANSACTION_COMMENT_DELETED: 'TRANSACTION_COMMENT_DELETED',
  TRANSACTION_COMMENT_INVALID_CURSOR: 'TRANSACTION_COMMENT_INVALID_CURSOR',
  TRANSACTION_SCHEDULE_PARENT_NOT_RECURRING: 'TRANSACTION_SCHEDULE_PARENT_NOT_RECURRING',
  TRANSACTION_SCHEDULE_ALREADY_EXISTS: 'TRANSACTION_SCHEDULE_ALREADY_EXISTS',
  TRANSACTION_SCHEDULE_NOT_FOUND: 'TRANSACTION_SCHEDULE_NOT_FOUND',
  TRANSACTION_SCHEDULE_INVALID_CRON: 'TRANSACTION_SCHEDULE_INVALID_CRON',
  TRANSACTION_SCHEDULE_INVALID_INTERVAL: 'TRANSACTION_SCHEDULE_INVALID_INTERVAL',
  TRANSACTION_SCHEDULE_INVALID_END_DATE: 'TRANSACTION_SCHEDULE_INVALID_END_DATE',
  TRANSACTION_SCHEDULE_INVALID_SPEC: 'TRANSACTION_SCHEDULE_INVALID_SPEC',
  TRANSACTION_SCHEDULE_ALREADY_PAUSED: 'TRANSACTION_SCHEDULE_ALREADY_PAUSED',
  TRANSACTION_SCHEDULE_NOT_PAUSED: 'TRANSACTION_SCHEDULE_NOT_PAUSED',
  TRANSACTION_SCHEDULE_CANCELLED: 'TRANSACTION_SCHEDULE_CANCELLED',
  TRANSACTION_SCHEDULE_ALREADY_CANCELLED: 'TRANSACTION_SCHEDULE_ALREADY_CANCELLED',
  TRANSACTION_SCHEDULE_PAST_END: 'TRANSACTION_SCHEDULE_PAST_END',
  TRANSACTION_OCCURRENCE_CREATED: 'TRANSACTION_OCCURRENCE_CREATED',
  TRANSACTION_PLAN_REQUIRED: 'TRANSACTION_PLAN_REQUIRED',
  TRANSACTION_PLAN_INVALID: 'TRANSACTION_PLAN_INVALID',
  TRANSACTION_PLAN_NOT_FOUND: 'TRANSACTION_PLAN_NOT_FOUND',
  TRANSACTION_PLAN_ALREADY_CANCELLED: 'TRANSACTION_PLAN_ALREADY_CANCELLED',
  // Phase 20.2 — accounts and transfers (design §6.3).
  // NOT_FOUND also covers "archived" and "not visible": a caller must never
  // learn that an account they cannot use exists.
  TRANSACTION_ACCOUNT_NOT_FOUND: 'TRANSACTION_ACCOUNT_NOT_FOUND',
  TRANSACTION_ACCOUNT_CURRENCY_MISMATCH: 'TRANSACTION_ACCOUNT_CURRENCY_MISMATCH',
  TRANSACTION_TRANSFER_INVALID: 'TRANSACTION_TRANSFER_INVALID',
} as const;

export type TransactionErrorCode = (typeof TRANSACTION_ERRORS)[keyof typeof TRANSACTION_ERRORS];
