packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - cpu-features
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
