/**
 * Payment-domain error codes — see design §5.7.
 *
 * Only the subset used by the POST /payments (ONE_TIME) endpoint lives here
 * for iteration 6.5. Later iterations (list/get/edit/delete, stars, comments,
 * RECURRING, INSTALLMENT) will extend this union.
 */
export const PAYMENT_ERRORS = {
  PAYMENT_INVALID_AMOUNT: 'PAYMENT_INVALID_AMOUNT',
  PAYMENT_INVALID_DATE: 'PAYMENT_INVALID_DATE',
  PAYMENT_INVALID_CURRENCY: 'PAYMENT_INVALID_CURRENCY',
  PAYMENT_INVALID_CATEGORY: 'PAYMENT_INVALID_CATEGORY',
  PAYMENT_CATEGORY_DIRECTION_MISMATCH: 'PAYMENT_CATEGORY_DIRECTION_MISMATCH',
  PAYMENT_NO_ATTRIBUTIONS: 'PAYMENT_NO_ATTRIBUTIONS',
  PAYMENT_INVALID_ATTRIBUTION: 'PAYMENT_INVALID_ATTRIBUTION',
  PAYMENT_ATTRIBUTION_OUT_OF_SCOPE: 'PAYMENT_ATTRIBUTION_OUT_OF_SCOPE',
  PAYMENT_DUPLICATE_ATTRIBUTION: 'PAYMENT_DUPLICATE_ATTRIBUTION',
  PAYMENT_SCHEDULE_NOT_SUPPORTED: 'PAYMENT_SCHEDULE_NOT_SUPPORTED',
  PAYMENT_PLAN_NOT_SUPPORTED: 'PAYMENT_PLAN_NOT_SUPPORTED',
  PAYMENT_TYPE_NOT_IMPLEMENTED: 'PAYMENT_TYPE_NOT_IMPLEMENTED',
  PAYMENT_SCOPE_NOT_ACCESSIBLE: 'PAYMENT_SCOPE_NOT_ACCESSIBLE',
  PAYMENT_INVALID_CURSOR: 'PAYMENT_INVALID_CURSOR',
} as const;

export type PaymentErrorCode = (typeof PAYMENT_ERRORS)[keyof typeof PAYMENT_ERRORS];
