export const GROUP_ERRORS = {
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  NOT_A_MEMBER: 'GROUP_NOT_A_MEMBER',
  NOT_AN_ADMIN: 'GROUP_NOT_AN_ADMIN',
  ALREADY_A_MEMBER: 'GROUP_ALREADY_A_MEMBER',
  INVITE_TOKEN_INVALID: 'GROUP_INVITE_TOKEN_INVALID',
  INVITE_TOKEN_EXPIRED: 'GROUP_INVITE_TOKEN_EXPIRED',
  INVITE_TOKEN_USED: 'GROUP_INVITE_TOKEN_USED',
  CANNOT_REMOVE_LAST_ADMIN: 'GROUP_CANNOT_REMOVE_LAST_ADMIN',
  CANNOT_LEAVE_AS_LAST_ADMIN: 'GROUP_CANNOT_LEAVE_AS_LAST_ADMIN',
  CANNOT_REMOVE_SELF: 'GROUP_CANNOT_REMOVE_SELF',
} as const;
