-- Phase 8, iteration 8.25 — product_images (expand step). Up to
-- PRODUCT_IMAGE_MAX_COUNT pictures per product; position 1 = primary.
-- Backfills one row per product with an existing image_ref: the stored
-- 512px WebP sits at `<base>.webp`, so `base_ref` = image_ref minus the
-- `.webp` suffix serves immediately. The AVIF + thumbnail renditions are
-- regenerated by the bootstrap backfill sweep (design §3.4).
-- `products.image_ref` is dropped by the contract migration after the
-- code cutover (design §3.1).

-- CreateTable
CREATE TABLE `product_images` (
    `id` VARCHAR(36) NOT NULL,
    `product_id` VARCHAR(36) NOT NULL,
    `position` INTEGER NOT NULL,
    `base_ref` VARCHAR(500) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `product_images_product_id_position_key`(`product_id`, `position`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `product_images` ADD CONSTRAINT `product_images_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- Backfill: every product with a processed image gets a position-1 row.
INSERT INTO `product_images` (`id`, `product_id`, `position`, `base_ref`)
SELECT UUID(), `id`, 1, SUBSTRING(`image_ref`, 1, CHAR_LENGTH(`image_ref`) - 5)
FROM `products`
WHERE `image_ref` IS NOT NULL AND `image_ref` LIKE '%.webp';
