/**
 * Phase 8 — structured error codes for the product registry & matching
 * pipeline (design §3). Mirrors the RECEIPT_ERRORS convention.
 */
export const PRODUCT_ERRORS = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_INVALID_BARCODE: 'PRODUCT_INVALID_BARCODE',
  PRODUCT_BARCODE_TAKEN: 'PRODUCT_BARCODE_TAKEN',
  PRODUCT_INVALID_CATEGORY: 'PRODUCT_INVALID_CATEGORY',
  PRODUCT_INVALID_IMAGE: 'PRODUCT_INVALID_IMAGE',
  PRODUCT_IMAGE_TOO_LARGE: 'PRODUCT_IMAGE_TOO_LARGE',
  PRODUCT_IMAGE_LIMIT_REACHED: 'PRODUCT_IMAGE_LIMIT_REACHED',
  PRODUCT_MATCH_INVALID: 'PRODUCT_MATCH_INVALID',
} as const;

export type ProductErrorCode = (typeof PRODUCT_ERRORS)[keyof typeof PRODUCT_ERRORS];
