export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  TOKEN_REUSE_DETECTED: 'AUTH_TOKEN_REUSE_DETECTED',
  REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  VALIDATION_ERROR: 'AUTH_VALIDATION_ERROR',
} as const;
